2021-02-17 19:21:45,110 INFO    MainThread:232692 [wandb_setup.py:_flush():70] setting env: {}
2021-02-17 19:21:45,110 INFO    MainThread:232692 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-02-17 19:21:45,111 INFO    MainThread:232692 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-17 19:21:45,111 INFO    MainThread:232692 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-17 19:21:45,111 INFO    MainThread:232692 [wandb_init.py:_log_setup():303] Logging user logs to /home/tyna/Documents/safe-experts/algos/wandb/run-20210217_192145-2ijm79vl/logs/debug.log
2021-02-17 19:21:45,111 INFO    MainThread:232692 [wandb_init.py:_log_setup():304] Logging internal logs to /home/tyna/Documents/safe-experts/algos/wandb/run-20210217_192145-2ijm79vl/logs/debug-internal.log
2021-02-17 19:21:46,117 INFO    MainThread:232692 [wandb_run.py:_console_start():1237] atexit reg
2021-02-17 19:21:46,118 INFO    MainThread:232692 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.REDIRECT
2021-02-17 19:21:46,118 INFO    MainThread:232692 [wandb_run.py:_redirect():1107] Redirecting console.
2021-02-17 19:21:46,118 INFO    MainThread:232692 [redirect.py:install():204] install start
2021-02-17 19:21:46,119 INFO    MainThread:232692 [redirect.py:install():219] install stop
2021-02-17 19:21:46,119 INFO    MainThread:232692 [redirect.py:install():204] install start
2021-02-17 19:21:46,119 INFO    MainThread:232692 [redirect.py:install():219] install stop
2021-02-17 19:21:46,119 INFO    MainThread:232692 [wandb_run.py:_redirect():1151] Redirects installed.
2021-02-17 19:21:50,222 INFO    MainThread:232692 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 1
2021-02-17 19:21:50,224 INFO    MainThread:232692 [wandb_run.py:_restore():1179] restore
2021-02-17 19:21:50,224 INFO    MainThread:232692 [redirect.py:uninstall():223] uninstall start
2021-02-17 19:21:50,224 INFO    MainThread:232692 [redirect.py:_stop():278] _stop: stdout
2021-02-17 19:21:50,224 INFO    stdout    :232692 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2021-02-17 19:21:50,225 INFO    MainThread:232692 [redirect.py:_stop():284] _stop closed: stdout
2021-02-17 19:21:50,225 INFO    stdout    :232692 [redirect.py:_pipe_relay():136] relay done done: stdout
2021-02-17 19:21:50,225 INFO    MainThread:232692 [redirect.py:_stop():290] _stop joined: stdout
2021-02-17 19:21:50,225 INFO    MainThread:232692 [redirect.py:_stop():292] _stop rd closed: stdout
2021-02-17 19:21:50,225 INFO    MainThread:232692 [redirect.py:uninstall():227] uninstall done
2021-02-17 19:21:50,225 INFO    MainThread:232692 [redirect.py:uninstall():223] uninstall start
2021-02-17 19:21:50,225 INFO    MainThread:232692 [redirect.py:_stop():278] _stop: stderr
2021-02-17 19:21:50,225 INFO    MainThread:232692 [redirect.py:_stop():284] _stop closed: stderr
2021-02-17 19:21:50,225 INFO    stderr    :232692 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2021-02-17 19:21:50,225 INFO    stderr    :232692 [redirect.py:_pipe_relay():136] relay done done: stderr
2021-02-17 19:21:50,225 INFO    MainThread:232692 [redirect.py:_stop():290] _stop joined: stderr
2021-02-17 19:21:50,225 INFO    MainThread:232692 [redirect.py:_stop():292] _stop rd closed: stderr
2021-02-17 19:21:50,225 INFO    MainThread:232692 [redirect.py:uninstall():227] uninstall done
2021-02-17 19:21:50,227 INFO    MainThread:232692 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "382088224f1d473d95954530032aac05"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 747
      total_bytes: 747
    }
  }
}

2021-02-17 19:21:52,231 INFO    MainThread:232692 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "fafa7c2b977a496d92b871284ce8a079"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 6742
      total_bytes: 6742
    }
  }
}

2021-02-17 19:21:54,236 INFO    MainThread:232692 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "659b51853c5c42e0bf7a0b84eecae8c0"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 6742
      total_bytes: 6742
    }
  }
}

2021-02-17 19:21:55,341 INFO    MainThread:232692 [wandb_run.py:_show_files():1536] logging synced files
2021-02-17 19:21:55,343 INFO    MainThread:232692 [internal.py:handle_exit():138] Internal process exited
